
package com.ibm.jaxws.tutorial.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://ws.mkyong.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param requestData
     * @return
     *     returns com.ibm.jaxws.tutorial.service.client.ResponseData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://ws.mkyong.com/", className = "com.ibm.jaxws.tutorial.service.client.GetHelloWorld")
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://ws.mkyong.com/", className = "com.ibm.jaxws.tutorial.service.client.GetHelloWorldResponse")
    @Action(input = "http://ws.mkyong.com/HelloWorld/getHelloWorldRequest", output = "http://ws.mkyong.com/HelloWorld/getHelloWorldResponse")
    public ResponseData getHelloWorld(
        @WebParam(name = "requestData", targetNamespace = "")
        RequestData requestData);

}
